name: Kickoff release

on: [workflow_dispatch]

permissions:
  pull-requests: write

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Create PR to push main to release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "gh pr create --title 'chore: kickoff release' --body 'kickoff release' --head main --base release"
